package com.asksunny.schema;

public enum DataGenType {
	REF, SEQUENCE, DATE, TIME, TIMESTAMP, STRING, FORMATTED_STRING, FIRST_NAME, LAST_NAME, SSN, STREET, CITY, STATE, ZIP_US, LONG, INT,  DOUBLE, FLOAT, ULONG, UINT, UDOUBLE, UFLOAT, BINARY, BIGINTEGER, BIGDECIMAL, ENUM
}
